language: php
php:
  - '7.1'

services:
  - docker
 
before-install:
  - pip install awscli

before_script:
  - composer self-update
  - git clone --branch=8.x https://github.com/dru-io/Dru.io.git /opt/druio-html

script:
  - composer update --with-dependencies -d /opt/druio-html
  - tar czf druio.tar.gz /html

after_success:
  - echo 'ok'
