language: python
python:
    - '2.7'

services:
  - docker

script:
  - git clone --branch=8.x https://github.com/dru-io/Dru.io.git /opt/druio-html

after_success:
  - echo \#\!/bin/bash > /opt/composer.sh
  - echo -e "\n\ncomposer update --with-dependencies -d /var/www/html\n" >> /opt/composer.sh
  - chmod +x /opt/composer.sh
  - cat /opt/composer.sh
  - docker run -ti -v /opt/druio-html:/var/www/html:rw -v /opt/composer.sh:/start.sh:ro synst/php7
  - cd /opt/druio-html && ls -l
  - docker run -ti -v /opt/druio-html:/html:rw -e "S3_BUCKET_NAME=druio" -e "AWS_DEFAULT_REGION=eu-west-1" -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e "BACKUP_NAME=druio" -e "BACKUP_PATHS=/html" -e "BACKUP_TAR_OPTION=" synst/s3-dockup
