language: php
php:
  - '7.1'

services:
  - docker

before-install:
  - composer self-update

script:
  - composer update --with-dependencies

after_success:
  - echo \#\!/bin/bash > /opt/composer.sh
