language: php
php:
  - '7.1'

services:
  - docker

before-install:
  - composer self-update
  - git clone --branch=8.x https://github.com/dru-io/Dru.io.git /opt/druio-html
  - cd /opt/druio-html

script:
  - composer update --with-dependencies

after_success:
  - echo 'ok'
